apiVersion: v1
kind: Service
metadata:
  namespace: { { .Values.application.namespace } }
  name: { { include "gs-users.fullname" . } }
  labels: { { - include "gs-users.labels" . | nindent 4 } }
spec:
  type: { { .Values.service.type } }
  ports:
    - port: { { .Values.service.port } }
      targetPort: { { .Values.service.port } }
      protocol: TCP
      name: User Service Port
  selector: { { - include "gs-users.selectorLabels" . | nindent 4 } }
